# Análise Estatística — TCP vs R-UDP

**PPGCC/UFPI · Redes de Computadores 2026-1 — Projeto Fase 1**
Transferência de arquivos cliente/servidor em containers Docker.

Comparação entre **TCP nativo** e **R-UDP** (UDP confiável, Go-Back-N com janela de 8
segmentos) sob três cenários de rede emulados com `tc netem`.

| Cenário | Perda | Atraso (one-way) |
|---------|-------|------------------|
| **A** | 0%  | 10 ms |
| **B** | 10% | 50 ms |
| **C** | 20% | 100 ms |

> **Metodologia de rede (importante).** O `netem` é aplicado no *egress* dos dois
> containers de forma **assimétrica**: o **cliente** (caminho de DADOS,
> cliente→servidor) recebe **atraso + perda** do cenário; o **servidor** (caminho de
> ACK, servidor→cliente) recebe **apenas o atraso**, sem perda. Assim `RTT ≈ 2 × atraso`
> e a **perda incide sobre os DADOS**, exercitando plenamente a retransmissão do R-UDP.
> Essa escolha evita as tempestades de RTO que a perda *bidirecional* de 20% impõe ao
> TCP (que levavam uma transferência de 1 MB a mais de 5 min), mantendo a bateria
> viável. Degradar **apenas o servidor** (só ACKs) deixaria o caminho de DADOS sem
> perda e a retransmissão do R-UDP praticamente inativa.

**Dados:** N repetições × 2 modos × 3 cenários. Arquivo `test_1MB.bin`
(1.048.576 B = 256 blocos de 4.096 B). Métricas da aplicação em JSONL; tráfego de
rede em `.pcap`/CSV via `tcpdump`.

In [1]:
# Em Google Colab, descomente a linha abaixo e faça upload de logs/ (ou monte o Drive):
# !pip install -q plotly pandas numpy kaleido

import os
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display

# ── Diretório de trabalho: garante a raiz do repositório ──────────────────────
if not os.path.exists('logs/app/client_transfers.jsonl') and \
   os.path.exists('../logs/app/client_transfers.jsonl'):
    os.chdir('..')   # kernel iniciou em notebooks/
print('cwd:', os.getcwd())

# ── Caminhos ──────────────────────────────────────────────────────────────────
CLI_JSONL    = 'logs/app/client_transfers.jsonl'
SRV_JSONL    = 'logs/app/server_transfers.jsonl'
PCAP_SUMMARY = 'logs/csv/pcap_summary.csv'
FIG_DIR, TAB_DIR = 'results/figures', 'results/tables'
os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(TAB_DIR, exist_ok=True)

# ── Recorte da bateria ────────────────────────────────────────────────────────
# A bateria (perda no caminho de DADOS) foi iniciada em 2026-05-29 00:29 UTC.
# Se re-executar a bateria, ajuste para o início do novo run
# (veja o timestamp em logs/app/battery_<AAAAMMDD_HHMMSS>.log).
BATTERY_START = pd.Timestamp('2026-05-29T00:29:30', tz='UTC')

# Nº de repetições por célula usado na análise (balanceia n caso a bateria tenha
# gravado repetições a mais). Ajuste conforme o nº de reps efetivamente rodadas.
TARGET_REPS = 10

# ── Constantes do experimento ─────────────────────────────────────────────────
FILE_SIZE  = 1_048_576
CHUNK_SIZE = 4096
N_BLOCKS   = FILE_SIZE // CHUNK_SIZE      # 256 blocos de dados por transferência

# ── Estética e helpers ────────────────────────────────────────────────────────
COLORS     = {'TCP': '#1E88E5', 'RUDP': '#E53935'}
SCEN_ORDER = {'scenario': ['A', 'B', 'C']}

def style(fig, title):
    fig.update_layout(template='plotly_white', font=dict(size=13),
                      title=dict(text=title, font=dict(size=16)),
                      legend_title_text='Protocolo')
    return fig

def save_fig(fig, name):
    """Exporta PNG (requer kaleido) e sempre um HTML interativo de fallback."""
    try:
        fig.write_image(f'{FIG_DIR}/{name}.png', width=950, height=520, scale=2)
        print(f'  figura salva: {FIG_DIR}/{name}.png')
    except Exception as e:
        fig.write_html(f'{FIG_DIR}/{name}.html')
        print(f'  PNG indisponível ({type(e).__name__}; instale kaleido) -> HTML: {FIG_DIR}/{name}.html')

# Bootstrap (sem scipy): IC de qualquer estatística por reamostragem com reposição
_rng = np.random.default_rng(42)
def boot_ci(x, stat=np.median, n_boot=5000, alpha=0.05):
    x = np.asarray(x, dtype=float)
    if x.size < 2:
        v = float(x[0]) if x.size else np.nan
        return v, v
    idx  = _rng.integers(0, x.size, size=(n_boot, x.size))
    dist = stat(x[idx], axis=1)
    return tuple(np.percentile(dist, [100 * alpha / 2, 100 * (1 - alpha / 2)]))

cwd: /home/anthonym/codes/redes_doutorado

## 1. Carregamento e recorte da bateria

In [2]:
df_cli = pd.read_json(CLI_JSONL, lines=True)
df_srv = pd.read_json(SRV_JSONL, lines=True)
df_cli['start_time'] = pd.to_datetime(df_cli['start_time'], utc=True)
df_srv['start_time'] = pd.to_datetime(df_srv['start_time'], utc=True)

cli = df_cli[df_cli['start_time'] >= BATTERY_START].copy()
srv = df_srv[df_srv['start_time'] >= BATTERY_START].copy()

# Balanceia n: usa as primeiras TARGET_REPS repetições de cada (modo, cenário)
cli = (cli.sort_values('start_time')
          .groupby(['mode', 'scenario'], group_keys=False).head(TARGET_REPS)
          .reset_index(drop=True))
srv = srv[srv['transfer_id'].isin(cli['transfer_id'])].reset_index(drop=True)

# Métricas derivadas
cli['throughput_KBps'] = cli['throughput_bytes_s'] / 1024.0
cli['overhead_blocks'] = cli['num_blocks'] / N_BLOCKS   # 1.0 = nenhuma retransmissão

assert len(cli) > 0, 'Nenhum registro após o filtro — ajuste BATTERY_START.'
print(f'Transferências carregadas — cliente: {len(cli)} | servidor: {len(srv)}')
print()
display(cli.groupby(['mode', 'scenario']).size().rename('n').unstack())

Transferências carregadas — cliente: 60 | servidor: 60

scenario   A   B   C
mode
RUDP      10  10  10
TCP       10  10  10

## 2. Validação de integridade

Cliente e servidor registram o **mesmo** `transfer_id` (UUID gerado pelo cliente e
propagado no cabeçalho TCP / no SYN do R-UDP). O *join* por esse campo permite
confrontar os dois lados e validar que o arquivo chegou íntegro (checksum MD5).

In [3]:
merged = cli.merge(srv, on='transfer_id', suffixes=('_cli', '_srv'))
checksum_ok = bool((merged['file_checksum_cli'] == merged['file_checksum_srv']).all())
status_ok   = bool(((merged['status_cli'] == 'success') &
                    (merged['status_srv'] == 'success')).all())

print(f'Transferências pareadas (join por transfer_id): {len(merged)} / {len(cli)}')
print(f'Checksums MD5 idênticos cliente<->servidor   : {checksum_ok}')
print(f'Todas as transferências com status=success    : {status_ok}')

Transferências pareadas (join por transfer_id): 60 / 60
Checksums MD5 idênticos cliente<->servidor   : True
Todas as transferências com status=success    : True

## 3. Tabela resumo — mediana [IC 95%] e média ± desvio

Sob perda, o tempo do R-UDP é fortemente **assimétrico** (poucas execuções muito
lentas dominam a média). Por isso reportamos a **mediana** com **IC 95% por
bootstrap** como medida central robusta, ao lado da tradicional média ± desvio
padrão exigida pela rubrica.

In [4]:
def metric_table(col, dec=3):
    rows = []
    for (m, s), g in cli.groupby(['mode', 'scenario']):
        x = g[col].to_numpy(dtype=float)
        lo, hi = boot_ci(x, np.median)
        rows.append({
            'Modo': m, 'Cenário': s, 'n': len(x),
            'Mediana':        f'{np.median(x):.{dec}f}',
            'IC 95% (mediana)': f'[{lo:.{dec}f}, {hi:.{dec}f}]',
            'Média ± DP':     f'{np.mean(x):.{dec}f} ± {(np.std(x, ddof=1) if len(x) > 1 else 0.0):.{dec}f}',
        })
    return pd.DataFrame(rows).set_index(['Modo', 'Cenário'])

print('TEMPO DE TRANSFERÊNCIA (s)')
display(metric_table('transfer_time_s', 3))
print('\nTHROUGHPUT (KB/s)')
display(metric_table('throughput_KBps', 1))
print('\nRETRANSMISSÕES (timeouts -> reenvio de janela Go-Back-N)')
display(metric_table('num_retransmissions', 1))

TEMPO DE TRANSFERÊNCIA (s)

               n  Mediana    IC 95% (mediana)       Média ± DP
Modo Cenário
RUDP A        10    0.675      [0.673, 0.677]    0.676 ± 0.003
     B        10   51.873    [48.610, 57.933]   53.165 ± 6.390
     C        10  144.865  [136.567, 152.588]  144.613 ± 8.559
TCP  A        10    0.103      [0.103, 0.103]    0.103 ± 0.000
     B        10   20.552    [16.942, 21.641]   19.543 ± 3.221
     C        10   75.162    [68.788, 80.704]   75.166 ± 6.839

THROUGHPUT (KB/s)

               n Mediana  IC 95% (mediana)     Média ± DP
Modo Cenário
RUDP A        10  1516.2  [1511.6, 1520.5]   1515.3 ± 6.5
     B        10    19.7      [17.8, 21.1]     19.5 ± 2.2
     C        10     7.1        [6.7, 7.5]      7.1 ± 0.4
TCP  A        10  9949.8  [9929.7, 9987.7]  9958.9 ± 36.9
     B        10    49.8      [47.4, 62.0]    54.0 ± 10.9
     C        10    13.6      [12.7, 14.9]     13.7 ± 1.2

RETRANSMISSÕES (timeouts -> reenvio de janela Go-Back-N)

               n Mediana IC 95% (mediana)    Média ± DP
Modo Cenário
RUDP A        10     0.0       [0.0, 0.0]     0.0 ± 0.0
     B        10    89.5    [82.5, 100.0]   91.1 ± 11.6
     C        10   240.0   [224.0, 252.5]  238.5 ± 15.5
TCP  A        10     0.0       [0.0, 0.0]     0.0 ± 0.0
     B        10     0.0       [0.0, 0.0]     0.0 ± 0.0
     C        10     0.0       [0.0, 0.0]     0.0 ± 0.0

In [5]:
# Tabela consolidada exportada para results/tables/summary_stats.csv
agg = cli.groupby(['mode', 'scenario']).agg(
    n             = ('transfer_time_s',     'count'),
    time_median_s = ('transfer_time_s',     'median'),
    time_mean_s   = ('transfer_time_s',     'mean'),
    time_std_s    = ('transfer_time_s',     'std'),
    tput_median_KBps = ('throughput_KBps',  'median'),
    tput_mean_KBps   = ('throughput_KBps',  'mean'),
    tput_std_KBps    = ('throughput_KBps',  'std'),
    retx_mean     = ('num_retransmissions', 'mean'),
    retx_std      = ('num_retransmissions', 'std'),
    retx_max      = ('num_retransmissions', 'max'),
    timeouts_mean = ('num_timeouts',        'mean'),
    blocks_mean   = ('num_blocks',          'mean'),
    overhead_mean = ('overhead_blocks',     'mean'),
).round(3)
agg.to_csv(f'{TAB_DIR}/summary_stats.csv')
print(f'Tabela consolidada exportada: {TAB_DIR}/summary_stats.csv')
display(agg)

Tabela consolidada exportada: results/tables/summary_stats.csv

                n  time_median_s  time_mean_s  time_std_s  tput_median_KBps  \
mode scenario
RUDP A         10          0.675        0.676       0.003          1516.198
     B         10         51.873       53.165       6.390            19.741
     C         10        144.865      144.613       8.559             7.071
TCP  A         10          0.103        0.103       0.000          9949.763
     B         10         20.552       19.543       3.221            49.827
     C         10         75.162       75.166       6.839            13.628

               tput_mean_KBps  tput_std_KBps  retx_mean  retx_std  retx_max  \
mode scenario
RUDP A               1515.267          6.536        0.0     0.000         0
     B                 19.493          2.158       91.1    11.571       113
     C                  7.104          0.424      238.5    15.451       258
TCP  A               9958.949         36.897        0.0     0.000         0
     B                 54.008         10.937        0.0     0.000         0
     C                 13.725          1.244        0.0     0.000         0

               timeouts_mean  blocks_mean  overhead_mean
mode scenario
RUDP A                   0.0        256.0          1.000
     B                  91.1        978.7          3.823
     C                 238.5       2142.6          8.370
TCP  A                   0.0        256.0          1.000
     B                   0.0        256.0          1.000
     C                   0.0        256.0          1.000

## Figura 1 — Tempo de transferência por cenário

Box plot com todos os pontos (escala log). O **cenário A** (0% de perda) isola o
efeito do **atraso**: o tempo reflete o RTT e o tamanho da janela. Nos cenários B/C
a perda passa a dominar, e o R-UDP expõe diretamente o custo das retransmissões,
enquanto o TCP trata a recuperação dentro do kernel.

In [6]:
fig1 = px.box(cli, x='scenario', y='transfer_time_s', color='mode',
              category_orders=SCEN_ORDER, color_discrete_map=COLORS, points='all',
              labels={'transfer_time_s': 'Tempo (s)', 'scenario': 'Cenário', 'mode': 'Protocolo'})
fig1.update_yaxes(type='log', title='Tempo de transferência (s — escala log)')
style(fig1, 'Fig. 1 — Tempo de transferência por cenário (TCP vs R-UDP)')
save_fig(fig1, 'fig1_tempo')
fig1.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig1_tempo.html

## Figura 2 — Throughput mediano por cenário

Barras = mediana do throughput; barras de erro = IC 95% (bootstrap). Escala log para
acomodar a diferença de ordens de grandeza entre TCP e R-UDP sob perda.

In [7]:
rows = []
for (m, s), g in cli.groupby(['mode', 'scenario']):
    x = g['throughput_KBps'].to_numpy(dtype=float)
    med = np.median(x); lo, hi = boot_ci(x, np.median)
    rows.append(dict(mode=m, scenario=s, median=med,
                     err_hi=max(hi - med, 0), err_lo=max(med - lo, 0)))
tp = pd.DataFrame(rows)

fig2 = px.bar(tp, x='scenario', y='median', color='mode', barmode='group',
              category_orders=SCEN_ORDER, color_discrete_map=COLORS,
              error_y='err_hi', error_y_minus='err_lo', text_auto='.1f',
              labels={'median': 'Throughput (KB/s)', 'scenario': 'Cenário', 'mode': 'Protocolo'})
fig2.update_yaxes(type='log', title='Throughput mediano (KB/s — escala log)')
style(fig2, 'Fig. 2 — Throughput mediano por cenário (IC 95% bootstrap)')
save_fig(fig2, 'fig2_throughput')
fig2.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig2_throughput.html

## Figura 3 — Retransmissões do R-UDP por cenário

Cada retransmissão é um evento de **timeout** que dispara o reenvio da janela
(Go-Back-N, janela = 8). Sob perda bidirecional o mecanismo é fortemente exercido —
e a forte dispersão revela a natureza estocástica da perda de pacotes.

In [8]:
rudp = cli[cli['mode'] == 'RUDP']
fig3 = px.box(rudp, x='scenario', y='num_retransmissions', category_orders=SCEN_ORDER,
              color_discrete_sequence=[COLORS['RUDP']], points='all',
              labels={'num_retransmissions': 'Nº de retransmissões', 'scenario': 'Cenário'})
style(fig3, 'Fig. 3 — Retransmissões R-UDP por cenário (Go-Back-N, janela = 8)')
fig3.update_layout(showlegend=False)
save_fig(fig3, 'fig3_retransmissoes')
fig3.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig3_retransmissoes.html

## Figura 4 — Custo da perda: volume de dados retransmitido (R-UDP)

`overhead = blocos enviados ÷ 256`. Valor **1,0** = arquivo enviado uma única vez
(sem retransmissão). Valores maiores quantificam o desperdício do Go-Back-N: cada
perda força o reenvio de toda a janela a partir do bloco perdido.

> O TCP tem overhead **1,0 no nível da aplicação** porque suas retransmissões ocorrem
> dentro do kernel, invisíveis às métricas da aplicação — só aparecem na rede
> (`tcpdump`, Fig. 5). Essa é justamente a diferença de *observabilidade* entre um
> protocolo confiável nativo e um implementado em espaço de usuário.

In [9]:
ov = (cli[cli['mode'] == 'RUDP']
      .groupby('scenario')['overhead_blocks'].agg(['mean', 'max']).reset_index())

fig4 = px.bar(ov, x='scenario', y='mean', category_orders=SCEN_ORDER,
              color_discrete_sequence=[COLORS['RUDP']], text_auto='.2f',
              labels={'mean': 'Overhead de dados (× tamanho do arquivo)', 'scenario': 'Cenário'})
fig4.add_hline(y=1.0, line_dash='dash', line_color='gray',
               annotation_text='1,0 = sem retransmissão', annotation_position='top left')
style(fig4, 'Fig. 4 — Overhead de retransmissão do R-UDP por cenário')
fig4.update_layout(showlegend=False)
save_fig(fig4, 'fig4_overhead')
fig4.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig4_overhead.html

## 4. Integração de dados — aplicação vs. `tcpdump`

Cada transferência gera dois registros independentes: as métricas internas da
aplicação (JSONL) e a captura externa na interface de rede (`.pcap` → CSV). O *join*
por `(modo, cenário, repetição)` permite confrontar **duração** e **volume de bytes**
medidos pela aplicação com o que de fato trafegou na rede.

In [10]:
pcap = pd.read_csv(PCAP_SUMMARY)
pcap['mode']    = pcap['mode'].str.upper()           # tcp->TCP, rudp->RUDP
pcap['rep_key'] = pcap['rep'].astype(int)

# rep sequencial por start_time dentro de cada (modo, cenário) -> casa com rep 01..N do pcap
cli_seq = cli.sort_values(['mode', 'scenario', 'start_time']).copy()
cli_seq['rep_key'] = cli_seq.groupby(['mode', 'scenario']).cumcount() + 1

xval = cli_seq.merge(pcap, on=['mode', 'scenario', 'rep_key'], how='inner')
print(f'Transferências com pcap pareado: {len(xval)} / {len(cli)}')

Transferências com pcap pareado: 60 / 60

### Figura 5 — Pacotes de dados na rede (captura `tcpdump`)

Número médio de pacotes cliente→servidor observados pelo `tcpdump`. O crescimento
sob perda evidencia as **retransmissões na rede** — para **ambos** os protocolos
(o TCP retransmite no kernel; o R-UDP, em espaço de usuário). É a contraprova externa
do overhead da Fig. 4.

In [11]:
wire = xval.groupby(['mode', 'scenario'])['pcap_c2s_pkts'].mean().reset_index()
fig5 = px.bar(wire, x='scenario', y='pcap_c2s_pkts', color='mode', barmode='group',
              category_orders=SCEN_ORDER, color_discrete_map=COLORS, text_auto='.0f',
              labels={'pcap_c2s_pkts': 'Pacotes cliente->servidor (tcpdump)', 'scenario': 'Cenário'})
style(fig5, 'Fig. 5 — Pacotes de dados na rede por cenário (tcpdump)')
save_fig(fig5, 'fig5_pacotes_rede')
fig5.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig5_pacotes_rede.html

### Figura 6 — Cross-validação de duração: aplicação vs. `tcpdump`

Cada ponto é uma transferência. Proximidade da reta `y = x` indica concordância entre
a duração medida pela aplicação (`time.monotonic`) e a janela de captura na rede.
Pequenos desvios sistemáticos são esperados e interpretáveis (handshake TCP capturado
antes de `send_file`; cálculo de checksum/serialização após o último pacote no R-UDP).

In [12]:
fig6 = px.scatter(xval, x='transfer_time_s', y='pcap_duration_s',
                  color='mode', symbol='scenario', color_discrete_map=COLORS, opacity=0.75,
                  labels={'transfer_time_s': 'Duração app / JSONL (s)',
                          'pcap_duration_s': 'Duração rede / tcpdump (s)',
                          'mode': 'Protocolo', 'scenario': 'Cenário'})
lo = max(min(xval['transfer_time_s'].min(), xval['pcap_duration_s'].min()) * 0.8, 1e-3)
hi = max(xval['transfer_time_s'].max(), xval['pcap_duration_s'].max()) * 1.2
fig6.add_trace(go.Scatter(x=[lo, hi], y=[lo, hi], mode='lines',
                          line=dict(dash='dash', color='gray', width=1), name='y = x'))
fig6.update_xaxes(type='log'); fig6.update_yaxes(type='log')
style(fig6, 'Fig. 6 — Cross-validação: duração app (JSONL) vs rede (tcpdump)')
save_fig(fig6, 'fig6_crossval')
fig6.show()

  PNG indisponível (ValueError; instale kaleido) -> HTML: results/figures/fig6_crossval.html

In [13]:
# Tabela de cross-validação: duração e bytes (app vs rede)
cv = xval.groupby(['mode', 'scenario']).agg(
    app_dur_s      = ('transfer_time_s', 'mean'),
    pcap_dur_s     = ('pcap_duration_s', 'mean'),
    app_bytes      = ('bytes_sent',      'mean'),
    pcap_c2s_bytes = ('pcap_c2s_bytes',  'mean'),
    pcap_c2s_pkts  = ('pcap_c2s_pkts',   'mean'),
).round(2)
cv['delta_dur_%'] = ((cv['pcap_dur_s'] - cv['app_dur_s']) / cv['app_dur_s'] * 100).round(1)
display(cv)

               app_dur_s  pcap_dur_s  app_bytes  pcap_c2s_bytes  \
mode scenario
RUDP A              0.68        2.15  1048576.0        941104.8
     B             53.17       52.42  1048576.0       3591692.8
     C            144.61      145.91  1048576.0       7046600.0
TCP  A              0.10        1.47  1048576.0        852300.0
     B             19.54       20.45  1048576.0        928187.2
     C             75.17       75.08  1048576.0        982282.4

               pcap_c2s_pkts  delta_dur_%
mode scenario
RUDP A                 234.1        216.2
     B                 874.4         -1.4
     C                1714.9          0.9
TCP  A                  95.2       1370.0
     B                 448.2          4.7
     C                 568.1         -0.1

## 5. Prova do `X-Custom-Auth` na captura

O campo obrigatório `X-Custom-Auth = Matrícula + Nome` viaja no cabeçalho da aplicação
(256 B) tanto no TCP quanto no payload do SYN do R-UDP, portanto deve ser visível no
`.pcap`. A célula abaixo extrai a string diretamente da captura via `tcpdump -A`.

In [14]:
import subprocess, shutil, glob

if shutil.which('docker') is None:
    print('docker indisponível (ex.: Colab) — verificação ao vivo pulada.')
    print('Localmente: docker exec ft-server tcpdump -r <pcap> -A | grep ANTHONY')
else:
    targets = (sorted(glob.glob('logs/pcap/capture_tcp_*.pcap'))[:1] +
               sorted(glob.glob('logs/pcap/capture_rudp_*.pcap'))[:1])
    for host_pcap in targets:
        name = os.path.basename(host_pcap)
        r = subprocess.run(
            ['docker', 'exec', 'ft-server', 'tcpdump', '-r', f'/app/logs/pcap/{name}', '-A'],
            capture_output=True, text=True)
        line = next((l.strip() for l in r.stdout.splitlines() if 'ANTHONY' in l), '')
        print(f'{name}: X-Custom-Auth presente = {bool(line)}')
        if line:
            print(f'   |- {line[:90]}')

capture_tcp_A_01.pcap: X-Custom-Auth presente = True
   |- .Ss.)w. RDFT........y4../.Mx.@+.Xm.-..20261011410 ANTHONY IRLAN MARQUES LUZ...............

capture_rudp_A_01.pcap: X-Custom-Auth presente = True
   |- .3....Yp................RDFT.........X....H5..1....R..20261011410 ANTHONY IRLAN MARQUES LU

## 6. Principais achados

In [15]:
def med(mode, sc, col):
    g = cli[(cli['mode'] == mode) & (cli['scenario'] == sc)]
    return float(np.median(g[col])) if len(g) else float('nan')

print('PRINCIPAIS ACHADOS (medianas)')
print('-' * 56)
print(f"Tempo TCP  A/B/C : {med('TCP','A','transfer_time_s'):.3f} / "
      f"{med('TCP','B','transfer_time_s'):.3f} / {med('TCP','C','transfer_time_s'):.3f} s")
print(f"Tempo RUDP A/B/C : {med('RUDP','A','transfer_time_s'):.3f} / "
      f"{med('RUDP','B','transfer_time_s'):.3f} / {med('RUDP','C','transfer_time_s'):.3f} s")
print(f"Overhead RUDP A/B/C (x arquivo): {med('RUDP','A','overhead_blocks'):.2f} / "
      f"{med('RUDP','B','overhead_blocks'):.2f} / {med('RUDP','C','overhead_blocks'):.2f}")
print(f"Retransm. RUDP B/C (mediana)   : {med('RUDP','B','num_retransmissions'):.0f} / "
      f"{med('RUDP','C','num_retransmissions'):.0f}")
print(f"Razão de lentidão RUDP/TCP em C : "
      f"{med('RUDP','C','transfer_time_s') / med('TCP','C','transfer_time_s'):.1f}x")

PRINCIPAIS ACHADOS (medianas)
--------------------------------------------------------
Tempo TCP  A/B/C : 0.103 / 20.552 / 75.162 s
Tempo RUDP A/B/C : 0.675 / 51.873 / 144.865 s
Overhead RUDP A/B/C (x arquivo): 1.00 / 3.77 / 8.43
Retransm. RUDP B/C (mediana)   : 90 / 240
Razão de lentidão RUDP/TCP em C : 1.9x

**Síntese (ver figuras e tabelas acima):**

1. **Integridade total.** 100% das transferências terminaram com `status=success` e
   checksum MD5 idêntico cliente↔servidor, em ambos os protocolos e nos três cenários:
   o R-UDP cumpre o objetivo de entrega íntegra sobre UDP.

2. **No cenário A (sem perda) o TCP é o baseline rápido**, com tempos baixos e variância
   mínima; o R-UDP paga apenas o custo de um ACK por janela.

3. **Sob perda, AMBOS os protocolos degradam — por mecanismos distintos.** O R-UDP expõe
   o custo de forma explícita: retransmissões e overhead de dados crescentes (Figs. 3–4)
   e tempo disparando no cenário C. O TCP degrada por **colapso da janela de
   congestionamento** (cada perda reduz a `cwnd`): o tempo no cenário C sobe muito acima
   do cenário A, embora suas retransmissões fiquem invisíveis às métricas de bloco da
   aplicação — só aparecem na rede (Fig. 5).

4. **Go-Back-N é ineficiente sob perda alta.** Como cada timeout reenvia a janela inteira
   a partir do bloco perdido, o volume retransmitido do R-UDP multiplica-se no cenário C
   — limitação conhecida que motivaria *Selective Repeat* em trabalho futuro.

5. **Distribuição assimétrica.** Como a perda é estocástica, poucas execuções "azaradas"
   dominam a média; por isso a **mediana com IC 95% (bootstrap)** é a medida central mais
   representativa nos cenários com perda.

6. **Observabilidade app vs. rede.** A cross-validação (Figs. 5–6) confirma a coerência
   entre as métricas internas (JSONL) e o `tcpdump`: a duração concorda dentro do esperado
   e o nº de pacotes na rede cresce com a perda, evidenciando as retransmissões de ambos
   os protocolos (no TCP, visíveis apenas na rede).